### ISSUE TITLE
Documentation: catching exceptions

### ISSUE THREAD

**Issue by RobjS** [alphagov/notifications-php-client#25]
The README recommends catching `Alphagov\Notifications\Exception\NotifyException` after trying the `sendEmail()` method, and then using `$e->getCode()` and `$e->getErrors()` to extract the exception info.

However the `->getErrors()` method only exists on the `ApiException` class, so can't be relied on to exist when catching the parent `NotifyException`, which only has standard RuntimeException methods.

**Comment by idavidmcdonald** [comment]
Sorry for the (very) long delay but I believe this has now been addressed in https://github.com/alphagov/notifications-php-client/pull/83. Feel free to reopen this issue if you think the issue still stands or if you think it needs further work.

Thanks for raising again :)
