### ISSUE TITLE
Requirement could not be resolved

### ISSUE THREAD

**Issue by dannyscarborough** [alphagov/notifications-php-client#60]
Hello,

I wondered if someone could help me with an issue whilst trying to install the PHP client?

I seem to be going around in circles when I'm trying to install the client using composer. 

If I run this command `composer require php-http/guzzle6-adapter alphagov/notifications-php-client`
it says:

> /guzzle6-adapter v2.0.1 requires php-http/httplug ^2.0

So I install php-http/httplug ^2.0 and run the command again and it says:

>  alphagov/notifications-php-client 1.6.2 requires php-http/httplug ^1.0 ->
satisfiable by php-http/httplug[v1.0.0, v1.0.0-RC1, v1.0.0-alpha, v1.0.0-alpha2,
 v1.0.0-alpha3, v1.0.0-beta, v1.1.0] but these conflict with your requirements o
r minimum-stability.

How can I install the client? it appears that it is only compatible with httplug v1 but guzzle 6 is only compatible with httplug v2

**Comment by leohemsted** [comment]
Hi @dannyscarborough, thanks for the issue

I've just released version 2.0.0 of the php-client (https://github.com/alphagov/notifications-php-client/pull/59), which should solve the issues. We here at GDS aren't PHP experts, so please let us know if this doesn't work.

Thanks,

Leo

**Comment by dannyscarborough** [comment]
@leohemsted Thank you, sorry I'm very new to this, how would I get 2.0.0? I tried `>composer require --dev alphagov/notifications-php-client ^2.0.0`

**Comment by dannyscarborough** [comment]
I ran `composer require alphagov/notifications-php-client:dev-master` and it appears to be working now. Thanks for your help @leohemsted 👍
