### ISSUE TITLE
Not using a direct PSR interface in client and instead using a httpplug wrapper around that interface.

### ISSUE THREAD

**Issue by cooperaj** [alphagov/notifications-php-client#67]
https://github.com/alphagov/notifications-php-client/blob/ae227d6d90fc1c3b0c09a1fca732439d62dcbd3c/src/Client.php#L119

We're trying to move to using the new 2.1 release of the client but have hit this issue. Our code uses PSR and injects a ClientInterface implementation into the NotifyClient constructor but this fails as it's expecting a HttpClientInterface (as linked above).

The thing is that HttpClientInterface is a direct wrapper, with no additional functionality over, ClientInterface. I'm loathed to bring in httpplug just so I can use this (but will if I have to)

**Comment by idavidmcdonald** [comment]
Hey @cooperaj, just tidying up our github issues and realised we hadn't closed this out.

I think issue was resolved in release v3.0.0 by https://github.com/alphagov/notifications-php-client/pull/72.

Please let me know if that isn't the case though by reopening the issue though!

Thanks
